apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-app
  namespace: argo
spec:
  project: default

  source:
    repoURL: https://github.com/veresattila2002/spring-boot-k8s.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-boot-app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
